version: "3"

services:
  web:
    build: ./environment/image
    image: enterprise
    ports:
      - "84:80"
      - "8084:22"
    volumes:
      - ../docroot:/var/www/html/
      - ./environment/apache2/sites-available:/etc/apache2/sites-available/
      - ./environment/apache2/sites-enabled:/etc/apache2/sites-enabled/
      - ./logs/apache2:/var/log/apache2/
    links:
      - db
  db:
    image: mysql:5.6
    entrypoint:
      - /localdb-run.sh
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - ./database:/var/lib/mysql/
      - ./environment/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./logs/mysql:/var/log/mysql/
      - ./environment/mysql/localdb-run.sh:/localdb-run.sh
